<h1>POSTTEST 7 KECERDASAN BUATAN</h1>
<a href="https://github.com/2009106055/Praktikum_KB">Link Github POSTTEST KB</a>

In [5]:
import numpy as np
import tensorflow as tf

<h5>Membuat Tensor Random dan Prime Tensor dengan shape [5,5]</h5>

In [9]:
random_tensor = tf.random.normal([5,5], mean=0, stddev=1, seed=1)
random_tensor

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[-0.32386488,  0.99133694,  0.14024267,  1.2573972 ,  0.09992335],
       [ 0.18983224, -0.28711194, -1.7413595 ,  1.8718754 , -2.0104504 ],
       [-1.4673029 , -1.2721989 , -0.7803738 ,  0.94073033, -0.06164822],
       [-2.0842526 ,  0.61423135, -1.451092  , -0.88693523, -0.96740866],
       [ 0.94831836, -0.6974499 ,  0.5391437 , -0.52970064, -2.0105364 ]],
      dtype=float32)>

In [10]:
prime_tensor = tf.constant([2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 71, 73, 79, 83, 89, 97, 101], shape=[5, 5], dtype=tf.float32)
prime_tensor

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[  2.,   3.,   5.,   7.,  11.],
       [ 13.,  17.,  19.,  23.,  29.],
       [ 31.,  37.,  41.,  43.,  47.],
       [ 53.,  59.,  61.,  71.,  73.],
       [ 79.,  83.,  89.,  97., 101.]], dtype=float32)>

<h5>Menampilkan hasil dari perhitungan aritmetika 2 variable tersebut (Gunakan minimal 5 operator)</h5>

<h5>Perhitungan aritmatika add (pertambahan)<h5>

In [11]:
tf.add(random_tensor,prime_tensor)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[ 1.6761351,  3.9913368,  5.1402426,  8.257397 , 11.099923 ],
       [13.189833 , 16.712889 , 17.25864  , 24.871876 , 26.98955  ],
       [29.532698 , 35.727802 , 40.219627 , 43.94073  , 46.93835  ],
       [50.91575  , 59.61423  , 59.54891  , 70.11307  , 72.03259  ],
       [79.94832  , 82.30255  , 89.53915  , 96.4703   , 98.98946  ]],
      dtype=float32)>

<h5>Perhitungan aritmatika substract (pengurangan)<h5>

In [12]:
tf.subtract(random_tensor,prime_tensor)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[  -2.323865 ,   -2.0086632,   -4.8597574,   -5.742603 ,
         -10.900077 ],
       [ -12.810167 ,  -17.287111 ,  -20.74136  ,  -21.128124 ,
         -31.01045  ],
       [ -32.467304 ,  -38.272198 ,  -41.780373 ,  -42.05927  ,
         -47.06165  ],
       [ -55.08425  ,  -58.38577  ,  -62.45109  ,  -71.88693  ,
         -73.96741  ],
       [ -78.05168  ,  -83.69745  ,  -88.46085  ,  -97.5297   ,
        -103.01054  ]], dtype=float32)>

<h5>Perhitungan aritmatika multiply (perkalian)<h5>

In [13]:
tf.multiply(random_tensor,prime_tensor)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[  -0.64772975,    2.974011  ,    0.70121336,    8.801781  ,
           1.0991569 ],
       [   2.4678192 ,   -4.880903  ,  -33.08583   ,   43.053135  ,
         -58.303062  ],
       [ -45.48639   ,  -47.07136   ,  -31.995327  ,   40.451405  ,
          -2.8974664 ],
       [-110.465385  ,   36.23965   ,  -88.51661   ,  -62.9724    ,
         -70.620834  ],
       [  74.91715   ,  -57.888344  ,   47.983788  ,  -51.380962  ,
        -203.06418   ]], dtype=float32)>

<h5>Perhitungan aritmatika divide (pembagian)<h5>

In [14]:
tf.divide(random_tensor,prime_tensor)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[-0.16193244,  0.33044565,  0.02804853,  0.17962816,  0.00908394],
       [ 0.01460248, -0.01688894, -0.0916505 ,  0.08138589, -0.06932587],
       [-0.04733235, -0.03438376, -0.01903351,  0.02187745, -0.00131166],
       [-0.03932552,  0.0104107 , -0.02378839, -0.01249205, -0.01325217],
       [ 0.01200403, -0.00840301,  0.00605779, -0.00546083, -0.0199063 ]],
      dtype=float32)>

<h5>Perhitungan aritmatika pow (pangkat)<h5>

In [15]:
tf.pow(random_tensor,prime_tensor)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[ 1.0488846e-01,  9.7423530e-01,  5.4250133e-05,  4.9694390e+00,
         9.9160073e-12],
       [ 4.1572837e-10, -6.1216887e-10, -3.7746809e+04,  1.8296565e+06,
        -6.2446387e+08],
       [-1.4524903e+05, -7.3881514e+03, -3.8406979e-05,  7.2277203e-02,
        -0.0000000e+00],
       [-8.0235882e+16,  3.2477805e-13, -7.3011604e+09, -1.9967581e-04,
        -8.9028239e-02],
       [ 1.5113972e-02, -1.0270262e-13,  1.3234340e-24, -1.7019940e-27,
        -4.3102917e+30]], dtype=float32)>

<h5>Menampilkan nilai maksimal dan minimal dari variable random_tensor</h5>

In [17]:
tf.argmax(random_tensor, axis=0)

<tf.Tensor: shape=(5,), dtype=int64, numpy=array([4, 0, 4, 1, 0], dtype=int64)>

In [24]:
tf.argmin(random_tensor, axis=0)

<tf.Tensor: shape=(5,), dtype=int64, numpy=array([3, 2, 1, 3, 4], dtype=int64)>

<h5>Tampilkan hasil dari penggabungan variable random_tensor dengan prime_tensor (concatenation)</h5>

In [27]:
print("size original pada data random dan prime tensor:",random_tensor.shape,prime_tensor.shape)
concated_tensor = tf.concat([random_tensor,prime_tensor],axis=0)
print("size concatenated data:",concated_tensor.shape)

size original pada data random dan prime tensor: (5, 5) (5, 5)
size concatenated data: (10, 5)


<h5>Tampilkan hasil sorting dari kedua variable di atas. (descending)</h5>

In [30]:
print("input prime tensor:",prime_tensor.numpy())
print("input random tensor:",random_tensor.numpy())
sorted_random = tf.sort(random_tensor, direction = "DESCENDING")
print("hasil random tensor sorted dengan descending order:",sorted_random.numpy())
sorted_prime = tf.sort(prime_tensor, direction = "DESCENDING")
print("hasil prime tensor sorted dengan descending order:",sorted_prime.numpy())

input prime tensor: [[  2.   3.   5.   7.  11.]
 [ 13.  17.  19.  23.  29.]
 [ 31.  37.  41.  43.  47.]
 [ 53.  59.  61.  71.  73.]
 [ 79.  83.  89.  97. 101.]]
input random tensor: [[-0.32386488  0.99133694  0.14024267  1.2573972   0.09992335]
 [ 0.18983224 -0.28711194 -1.7413595   1.8718754  -2.0104504 ]
 [-1.4673029  -1.2721989  -0.7803738   0.94073033 -0.06164822]
 [-2.0842526   0.61423135 -1.451092   -0.88693523 -0.96740866]
 [ 0.94831836 -0.6974499   0.5391437  -0.52970064 -2.0105364 ]]
hasil random tensor sorted dengan descending order: [[ 1.2573972   0.99133694  0.14024267  0.09992335 -0.32386488]
 [ 1.8718754   0.18983224 -0.28711194 -1.7413595  -2.0104504 ]
 [ 0.94073033 -0.06164822 -0.7803738  -1.2721989  -1.4673029 ]
 [ 0.61423135 -0.88693523 -0.96740866 -1.451092   -2.0842526 ]
 [ 0.94831836  0.5391437  -0.52970064 -0.6974499  -2.0105364 ]]
hasil prime tensor sorted dengan descending order: [[ 11.   7.   5.   3.   2.]
 [ 29.  23.  19.  17.  13.]
 [ 47.  43.  41.  37.  31.]