<h1>POSTTEST 7 KECERDASAN BUATAN</h1>
<a href="https://github.com/2009106055/Praktikum_KB">Link Github POSTTEST KB</a>

In [39]:
import numpy as np
import tensorflow as tf

<h5>Membuat Tensor Random dan Prime Tensor dengan shape [5,5]</h5>

In [40]:
random_tensor = tf.random.normal([5,5], mean=0, stddev=1, seed=1)
print("Tensor Random :",random_tensor.numpy())

Tensor Random : [[ 0.00534202 -1.0460438  -1.6427648  -0.3495337   0.951451  ]
 [ 0.8105827  -0.761741    1.0136645  -1.8470215   0.20171778]
 [ 1.2173525  -1.7574261   1.765832    1.14004     0.8317814 ]
 [-1.9974602   0.25176758  1.0689832   0.30159846  0.2641973 ]
 [ 0.02316601  0.7222838   0.3744623  -0.09558094  1.4185706 ]]


In [41]:
prime_tensor = tf.constant([2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 71, 73, 79, 83, 89, 97, 101], shape=[5, 5], dtype=tf.float32)
print("Tensor Prime",prime_tensor.numpy())

Tensor Prime [[  2.   3.   5.   7.  11.]
 [ 13.  17.  19.  23.  29.]
 [ 31.  37.  41.  43.  47.]
 [ 53.  59.  61.  71.  73.]
 [ 79.  83.  89.  97. 101.]]


<h5>Menampilkan hasil dari perhitungan aritmetika 2 variable tersebut (Gunakan minimal 5 operator)</h5>

<h5>Perhitungan aritmatika add (pertambahan)<h5>

In [42]:
print("Hasil Dari Pertambahan Tensor :",tf.add(random_tensor,prime_tensor).numpy())

Hasil Dari Pertambahan Tensor : [[  2.005342    1.9539562   3.3572352   6.6504664  11.951451 ]
 [ 13.810583   16.238258   20.013664   21.152979   29.201717 ]
 [ 32.217354   35.242573   42.76583    44.14004    47.83178  ]
 [ 51.00254    59.251766   62.068985   71.3016     73.2642   ]
 [ 79.02316    83.72228    89.374466   96.90442   102.41857  ]]


<h5>Perhitungan aritmatika substract (pengurangan)<h5>

In [43]:
print("Hasil Dari Pengurangan Tensor :",tf.subtract(random_tensor,prime_tensor).numpy())

Hasil Dari Pengurangan Tensor : [[ -1.994658   -4.046044   -6.642765   -7.3495336 -10.048549 ]
 [-12.189417  -17.761742  -17.986336  -24.847021  -28.798283 ]
 [-29.782648  -38.757427  -39.23417   -41.85996   -46.16822  ]
 [-54.99746   -58.748234  -59.931015  -70.6984    -72.7358   ]
 [-78.97684   -82.27772   -88.625534  -97.09558   -99.58143  ]]


<h5>Perhitungan aritmatika multiply (perkalian)<h5>

In [44]:
print("Hasil Dari Perkalian Tensor :",tf.multiply(random_tensor,prime_tensor).numpy())

Hasil Dari Perkalian Tensor : [[ 1.06840469e-02 -3.13813114e+00 -8.21382427e+00 -2.44673586e+00
   1.04659615e+01]
 [ 1.05375748e+01 -1.29495964e+01  1.92596245e+01 -4.24814949e+01
   5.84981537e+00]
 [ 3.77379265e+01 -6.50247650e+01  7.23991089e+01  4.90217209e+01
   3.90937271e+01]
 [-1.05865395e+02  1.48542871e+01  6.52079773e+01  2.14134903e+01
   1.92864017e+01]
 [ 1.83011508e+00  5.99495544e+01  3.33271446e+01 -9.27135181e+00
   1.43275635e+02]]


<h5>Perhitungan aritmatika divide (pembagian)<h5>

In [45]:
print("Hasil Dari Pembagian Tensor :",tf.divide(random_tensor,prime_tensor).numpy())

Hasil Dari Pembagian Tensor : [[ 2.6710117e-03 -3.4868124e-01 -3.2855296e-01 -4.9933385e-02
   8.6495548e-02]
 [ 6.2352516e-02 -4.4808295e-02  5.3350762e-02 -8.0305278e-02
   6.9557857e-03]
 [ 3.9269436e-02 -4.7498003e-02  4.3069072e-02  2.6512560e-02
   1.7697476e-02]
 [-3.7687927e-02  4.2672469e-03  1.7524315e-02  4.2478656e-03
   3.6191409e-03]
 [ 2.9324068e-04  8.7022139e-03  4.2074416e-03 -9.8537060e-04
   1.4045253e-02]]


<h5>Perhitungan aritmatika pow (pangkat)<h5>

In [46]:
print("Hasil Dari Perpangkatan Tensor :",tf.pow(random_tensor,prime_tensor).numpy())

Hasil Dari Perpangkatan Tensor : [[ 2.8537215e-05 -1.1445889e+00 -1.1964015e+01 -6.3741673e-04
   5.7842988e-01]
 [ 6.5217666e-02 -9.7886873e-03  1.2941672e+00 -1.3454100e+06
   6.8798849e-21]
 [ 4.4453607e+02 -1.1493494e+09  1.3332886e+10  2.8026218e+02
   1.7395316e-04]
 [-8.4205733e+15  4.5602440e-36  5.8509125e+01  1.0951345e-37
   0.0000000e+00]
 [ 0.0000000e+00  1.8739266e-12  0.0000000e+00 -0.0000000e+00
   2.1724390e+15]]


<h5>Menampilkan nilai maksimal dan minimal dari variable random_tensor</h5>

In [47]:
print("Hasil Dari Nilai Maximal Random Tensor :",tf.argmax(random_tensor, axis=0).numpy())

Hasil Dari Nilai Maximal Random Tensor : [2 4 2 2 4]


In [49]:
print("Hasil Dari Nilai Maximal Random Tensor :",tf.argmin(random_tensor, axis=0).numpy())

Hasil Dari Nilai Maximal Random Tensor : [3 2 0 1 1]


<h5>Tampilkan hasil dari penggabungan variable random_tensor dengan prime_tensor (concatenation)</h5>

In [50]:
print("size original pada data random dan prime tensor:",random_tensor.shape,prime_tensor.shape)
concated_tensor = tf.concat([random_tensor,prime_tensor],axis=0)
print("size concatenated data:",concated_tensor.shape)

size original pada data random dan prime tensor: (5, 5) (5, 5)
size concatenated data: (10, 5)


<h5>Tampilkan hasil sorting dari kedua variable di atas. (descending)</h5>

In [51]:
print("input prime tensor:",prime_tensor.numpy())
print("input random tensor:",random_tensor.numpy())
sorted_random = tf.sort(random_tensor, direction = "DESCENDING")
print("hasil random tensor sorted dengan descending order:",sorted_random.numpy())
sorted_prime = tf.sort(prime_tensor, direction = "DESCENDING")
print("hasil prime tensor sorted dengan descending order:",sorted_prime.numpy())

input prime tensor: [[  2.   3.   5.   7.  11.]
 [ 13.  17.  19.  23.  29.]
 [ 31.  37.  41.  43.  47.]
 [ 53.  59.  61.  71.  73.]
 [ 79.  83.  89.  97. 101.]]
input random tensor: [[ 0.00534202 -1.0460438  -1.6427648  -0.3495337   0.951451  ]
 [ 0.8105827  -0.761741    1.0136645  -1.8470215   0.20171778]
 [ 1.2173525  -1.7574261   1.765832    1.14004     0.8317814 ]
 [-1.9974602   0.25176758  1.0689832   0.30159846  0.2641973 ]
 [ 0.02316601  0.7222838   0.3744623  -0.09558094  1.4185706 ]]
hasil random tensor sorted dengan descending order: [[ 0.951451    0.00534202 -0.3495337  -1.0460438  -1.6427648 ]
 [ 1.0136645   0.8105827   0.20171778 -0.761741   -1.8470215 ]
 [ 1.765832    1.2173525   1.14004     0.8317814  -1.7574261 ]
 [ 1.0689832   0.30159846  0.2641973   0.25176758 -1.9974602 ]
 [ 1.4185706   0.7222838   0.3744623   0.02316601 -0.09558094]]
hasil prime tensor sorted dengan descending order: [[ 11.   7.   5.   3.   2.]
 [ 29.  23.  19.  17.  13.]
 [ 47.  43.  41.  37.  31.]